os: unstable
environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"

platform:
- x86
- x64

# Dropping support for node 4 on 32 windows because it has isuses with ssl certs and npm
matrix:
  exclude:
    - platform: x86
      nodejs_version: "4"

install:
- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
- ps: $env:Path += ";$(pwd)\node_modules\.bin";
- ps: >
    @{
      "nodejs_version" = $env:nodejs_version
      "platform" = $env:platform
      "node binary version" = $(node -v)
      "npm version" = $(npm -v)
      "APPVEYOR_REPO_COMMIT_MESSAGE" = $env:APPVEYOR_REPO_COMMIT_MESSAGE
    } | Out-String | Write-Host;

test_script:
- npm install serialport
- rd /s /q node_modules
- npm install serialport@beta

build: off
deploy: off
