os: unstable
environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: VM4yc2j2L3KS5qWLZLY7WUAXoqdB9YkodmXlHC2I+LSF0Y8a2cZ70M0+2+Fd5GkQ

  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"

platform:
  - x86
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - ps: $env:Path += ";$(pwd)\node_modules\.bin";
  - ps: >
      @{
        "nodejs_version" = $env:nodejs_version
        "platform" = $env:platform
        "node binary version" = $(node -v)
        "npm version" = $(npm -v)
        "APPVEYOR_REPO_COMMIT_MESSAGE" = $env:APPVEYOR_REPO_COMMIT_MESSAGE
      } | Out-String | Write-Host;

  # work around an issue with node-gyp v3.3.1 and node 4x
  # package.json has no certificates in it so we're cool
  # https://github.com/nodejs/node-gyp/issues/921
  - ps: npm config set -g cafile=package.json | Write-Host;
  - ps: npm config set -g strict-ssl=false | Write-Host;

test_script:
  - ps: npm install serialport

deploy: OFF
